# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  # ===================================================================
  # Database configuration
  # ===================================================================
  jpa:
    open-in-view: false
  datasource:
    url: ${PROD_DB_URL:jdbc:postgresql://localhost:5432/db_chatai}
    username: ${PROD_DB_USERNAME:}
    password: ${PROD_DB_PASSWORD:}
  # ===================================================================
  # RabbitMQ configuration
  # ===================================================================
  #  rabbitmq:
  #    host: 10.5.1.20
  #    port: 5672
  #    username: user-prod
  #    password: xxx-your-rabbitmq-password-xxx
  # ===================================================================
  # Logging and Tracing configuration
  # ===================================================================
#  zipkin:
#    base-url: http://10.5.1.20:9411/

